### Day 2 of 75 Days

### Multiple Linear Regression

In Day 1 , I learned about Simple Linear Regression, where a single Independent/Predictor(X) variable is used to model the response variable (Y). But there may be various cases in which the response variable is affected by more than one predictor variable; for such cases, the Multiple Linear Regression algorithm is used.

Moreover, Multiple Linear Regression is an extension of Simple Linear regression as it takes more than one predictor variable to predict the response variable.

#### Creating a House Price Prediction Model using Multiple Linear Regression

##### Code

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
data = pd.read_csv("homeprices.csv")
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
import math 
median_bedrooms = math.floor(data.bedrooms.median())
median_bedrooms

4

In [5]:
data.bedrooms=data.bedrooms.fillna(median_bedrooms)
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(data[['area','bedrooms','age']],data.price)

LinearRegression()

In [9]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [10]:
reg.intercept_

221323.00186540443

In [12]:
reg.predict([[3000,3,15]])

c:\Users\SURUCHI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([579201.19929613])

In [13]:
112.06244194*3000+23388.88007794*3+-3231.71790863*15+221323.00186540443

579201.1992897744

In [14]:
reg.predict([[2500,4,5]])

c:\Users\SURUCHI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

### Cost Function 

A cost function is an important parameter that determines how well a machine learning model performs for a given dataset. It calculates the difference between the expected value and predicted value and represents it as a single real number.

### Gradient Desent

"Gradient Descent is an optimization algorithm which is used for optimizing the cost function or error in the model." It enables the models to take the gradient or direction to reduce the errors by reaching to least possible error.

#### Done for Today